# theme: keep μ„¤μ • νμΌ μμ‹

menu:
  Home: /
  Archives: /archives/
  Projects: /projects/
  About: /about/



# μ†μ… λ§ν¬
social:
  github: https://github.com/goeun-oh
  email: mailto:goeun@example.com

portfolio:
  enable: true
  title: ν¬νΈν΄λ¦¬μ¤
  subtitle: ν”„λ΅μ νΈ λ¨μμ…λ‹λ‹¤.
  data_source: projects  # π”Ί μ΄κ±° κΌ­ ν•„μ”ν•©λ‹λ‹¤!
